[package]
name = "msolve"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"
sudoku = "0.7.0"

[[bench]]
name = "benchmarks"
harness = false
