[package]
name = "msolve"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"
include = ["src/lib.rs", "README.md"]

[dependencies]
smallvec = {version = "1.4.0", optional = true}

[dev-dependencies]
criterion = "0.3"
sudoku = "0.7.0"

[features]
default = ["smallvec"]


[[bench]]
name = "benchmarks"
harness = false

[profile.release]
debug = true
lto = true

[profile.dev]
opt-level = 3
debug-assertions = true
