[package]
name = "msolve"
description = "Another sudoku solving library"
version = "0.1.0"
authors = ["Alex Williams <mkb2191@protonmail.com>"]
edition = "2018"
include = ["src/lib.rs", "README.md", "benches/benchmarks.rs"]
repository = "https://github.com/mkb2091/msolve/"
license = "MIT"


[dependencies]
smallvec = {version = "1.4.0", optional = true}

[dev-dependencies]
criterion = "0.3"
quickcheck = "0.9"
quickcheck_macros = "0.9"
sudoku = "0.7.0"

[features]
default = ["smallvec"]


[[bench]]
name = "benchmarks"
harness = false

[profile.release]
debug = true
lto = true

[profile.dev]
opt-level = 3
debug-assertions = true
